service: github-lambda
frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.8
  region: eu-central-1
functions:
  hello:
    handler: handler.hello
plugins:
  - serverless-python-requirements
