name: deploy-lambda
env:
  RUNNER_PYTHON_VERSION               : "3.8"
  PYTHON_ENV                          : "python3.8"

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.RUNNER_PYTHON_VERSION }}

      - name: install aws cli
        run: |
          pip3 install awscli


      - name: Install  DE dependencies and create DE deployment package
        run: |
          python -m pip install --upgrade pip
          pip install -r de_requirements.txt -t .


      - name: Configure AWS Credentils
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      
           
